USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__LOAIPHONG__INSERT
@TENLOAIPHG		NVARCHAR(15),
@GIAPHG			INT
AS
BEGIN
	DECLARE @MALOAIPHG VARCHAR(10)
	SELECT @MALOAIPHG = dbo.FUNC__LOAIPHONG__GetNextID()
	
	INSERT INTO LOAIPHONG(MALOAIPHG, TENLOAIPHG, GIAPHG)
	VALUES (@MALOAIPHG, @TENLOAIPHG, @GIAPHG)
END
GO


--------------------------------------------------------
CREATE	PROC	PROC__LOAIPHONG__DELETE
@MALOAIPHG	VARCHAR(10)
AS
BEGIN
	DELETE FROM LOAIPHONG
	WHERE MALOAIPHG = @MALOAIPHG
END
GO


--------------------------------------------------------
CREATE	PROC	PROC__LOAIPHONG__UPDATE
@MALOAIPHG	VARCHAR(10),
@TENLOAIPHG	NVARCHAR(10),
@GIAPHG		INT
AS
BEGIN
	UPDATE LOAIPHONG
	SET TENLOAIPHG = @TENLOAIPHG,
		GIAPHG = @GIAPHG
	WHERE MALOAIPHG = @MALOAIPHG
END