CREATE DATABASE OCEAN_MOTEL
GO

USE OCEAN_MOTEL
GO


CREATE TABLE DANGNHAP
(
	TEN_TK				VARCHAR(20)					NOT NULL,
	MATKHAU				VARCHAR(100)				NOT NULL,
	HO					NVARCHAR(10)				NOT NULL,
	TEN					NVARCHAR(30)				NOT NULL,
	
	CONSTRAINT			PK__DANGNHAP				PRIMARY KEY(TEN_TK)
)
GO


CREATE TABLE KHU
(
	MA_KHU				VARCHAR(6),					--	VD: KHU001
	TEN_KHU				NVARCHAR(20)				NOT NULL,
	DTICH_KHU			INT 						NULL,
	MOTA				NVARCHAR(255)				NULL,
	SOLG_PHG			INT 						NOT NULL 					DEFAULT 0,
	
	CONSTRAINT			PK__KHU						PRIMARY KEY (MA_KHU)
)
GO


CREATE TABLE LOAI_PHONG
(
	MA_LOAIPHG			VARCHAR(7)					--	VD: LOAI007
	LOAI_PHG			NVARCHAR(20),				--	VIP		/	THƯỜNG
	GIA_PHG				BIGINT						NOT NULL,
	
	CONSTRAINT			PK__LOAI_PHONG				PRIMARY KEY(LOAI_PHG)
)
GO


CREATE TABLE PHONG
(
	MA_PHG				VARCHAR(7),
	TEN_PHG				NVARCHAR(20)				NOT NULL,
	LOAI_PHG			NVARCHAR(20)				NOT NULL,
	TEN_KHU				NVARCHAR(20)				NOT NULL,
	DIENTICH_PHG		INT 						NOT NULL					DEFAULT 0,
	SOLG_KHACH			INT 						NOT NULL					DEFAULT 0,
	
	CONSTRAINT			PK__PHONG					PRIMARY KEY(MA_PHG),
	CONSTRAINT			FK__PHONG__TEN_KHU			FOREIGN KEY(TEN_KHU)		REFERENCES KHU(TEN_KHU),
	CONSTRAINT			FK__PHONG__LOAI_PHG			FOREIGN KEY(LOAI_PHG)		REFERENCES LOAI_PHONG(LOAI_PHG)
)
GO


CREATE TABLE THIETBI_PHONG
(
	MA_TBI				VARCHAR(8)					--	VD: TBI00001,
	TEN_TBI				NVARCHAR(30)				NOT NULL,
	GIA_TBI				INT							NOT NULL,
	NGAYMUA_TBI			DATE						NOT NULL,
	MA_PHG				VARCHAR(7)					NOT NULL,
	
	CONSTRAINT			PK__THIETBI_PHONG			PRIMARY KEY(MA_THIET_BI, MA_PHG),
	CONSTRAINT			FK__THIETBI_PHONG__MA_PHG	FOREIGN KEY(MA_PHG)	 		REFERENCES PHONG(MA_PHG)
)
GO


CREATE TABLE DICHVU
(
	MA_DVU				VARCHAR(6),					--	VD:	DV0001
	TEN_DVU				NVARCHAR(50)				NOT NULL,

	CONSTRAINT			PK__DICHVU					PRIMARY KEY(MA_DVU)
)
GO


CREATE TABLE DICHVU_PHONG
(
	MA_PHG 				VARCHAR(7),
	MA_DVU				VARCHAR(6),

	CONSTRAINT			PK__DICHVU_PHONG			PRIMARY KEY(MA_PHG, MA_DVU)
	CONSTRAINT			FK__DICHVU_PHONG__MA_PHG	FOREIGN KEY(MA_PHG)			REFERENCES PHONG(MA_PHG),
	CONSTRAINT			FK__DICHVU_PHONG__MA_DVU	FOREIGN KEY(MA_DVU)			REFERENCES DICHVU(MA_DVU)
)
GO


CREATE TABLE KHACH
(
	MA_KHACH			VARCHAR(10),				--	VD: KHACH00001
	HO					NVARCHAR(10)				NOT NULL,
	TEN					NVARCHAR(30)				NOT NULL,
	GIOITINH			NVARCHAR(5)					NOT NULL,		--	Nam / Nữ / Khác
	NGAYSINH			DATE 						NOT NULL,
	CANCUOC				VARCHAR(20)					NOT NULL,
	DIACHI				NVARCHAR(75)				NOT NULL,
	MA_PHG				VARCHAR(7) 					NOT NULL,

	CONSTRAINT			PK__KHACH					PRIMARY KEY(MA_KHACH),
	CONSTRAINT			FK__KHACH__MA_PHG			FOREIGN KEY(MA_PHG)			REFERENCES PHONG (MA_PHG)
)


CREATE TABLE NGUOITHAN
(
	MA_NGTHAN			VARCHAR(11),
	HO					NVARCHAR(10)				NOT NULL,
	TEN					NVARCHAR(30)				NOT NULL,
	GIOITINH			NVARCHAR(5)					NOT NULL,
	NGAYSINH			DATE						NOT NULL,
	CANCUOC				VARCHAR(20)					NOT NULL,
	DIACHI				NVARCHAR(75)				NOT NULL,
	MA_KHACH			VARCHAR(10)					NOT NULL,

	CONSTRAINT			PK__NGUOITHAN				PRIMARY KEY(MA_NGTHAN),
	CONSTRAINT			FK__NGUOITHAN__MA_KHACH		FOREIGN KEY(MA_KHACH)		REFERENCES KHACH(MA_KHACH)
)
GO


CREATE TABLE VI_PHAM
(
	MA_VIPHAM			VARCHAR(12),				--	VD: VIPHAM00001
	NOIDUNG_VIPHAM		NVARCHAR(50),
	
	CONSTRAINT			PK__VI_PHAM					PRIMARY KEY(ID)
)
GO


CREATE TABLE KHACH_VIPHAM
(
	MA_VIPHAM			VARCHAR(12),
	MA_KHACH			VARCHAR(10),

	CONSTRAINT			PK__KHACH_VIPHAM			PRIMARY KEY(MA_VIPHAM, MA_KHACH),
	CONSTRAINT			FK__VI_PHAM__MA_VIPHAM		FOREIGN KEY(MA_VIPHAM)		REFERENCES VI_PHAM(MA_VIPHAM),
	CONSTRAINT			FK__VI_PHAM					FOREIGN KEY(MA_KHACH)		REFERENCES KHACH(MA_KHACH)
)
GO


CREATE TABLE DAT_PHONG
(
	MA_PHG				INT,
	NGAY_DAT			DATE NOT NULL,
	NGAY_TRA			DATE,
	MA_KHACH			VARCHAR(20)
)
GO


CREATE TABLE HOADON_CHITIEU
(
	MA_HOADON			INT			IDENTITY,
	MA_PHG				INT,
	TIEN_PHG			BIGINT,
	TIEN_DVU			BIGINT 
)
GO