USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__HOADON__INSERT
@#MAPHG		VARCHAR(10),
@#THANG		INT,
@#NAM		INT,
@#SODIEN		INT,
@#SONUOC		INT
AS
BEGIN
	DECLARE @#MAHOADON VARCHAR(15)
	SELECT @#MAHOADON = dbo.FUNC__HOADON__GetNextID()
	
	DECLARE @#TIENPHG INT
	SELECT @#TIENPHG = lp.GIAPHG
	FROM PHONG p, LOAIPHONG lp
	WHERE p.MAPHG = @#MAPHG
		AND lp.MALOAIPHG = p.MALOAIPHG
	
	INSERT INTO HOADON(MAHOADON, MAPHG, THANG, NAM, TIENPHONG)
	VALUES (@#MAHOADON, @#MAPHG, @#THANG, @#NAM, @#TIENPHG)
	
	EXEC PROC__HOADON_DICHVU__INSERT
	@MAHOADON = @#MAHOADON
	
	EXEC PROC__HOADON_DIENNUOC__INSERT
	@MAHOADON = @#MAHOADON,
	@SODIEN = @#SODIEN,
	@SONUOC = @#SONUOC
END
GO