USE QUAN_LY_PHONG_TRO
GO


CREATE	PROC	DANGNHAP__GETINFO
@TEN_TK		VARCHAR(20),
@MATKHAU	VARCHAR(100)
AS
	BEGIN
		SELECT *
		FROM DANGNHAP
		WHERE TEN_TK LIKE @TEN_TK
		 AND MATKHAU LIKE @MATKHAU
	END
GO


CREATE	PROC	DANGNHAP__INSERT
@TEN_TK		VARCHAR(20),
@MATKHAU	VARCHAR(100),
@LOAI_TK		INT,
@HO			NVARCHAR(10),
@TEN		NVARCHAR(20)
AS
	BEGIN
		INSERT INTO DANGNHAP(TEN_TK, MATKHAU, LOAI_TK, HO, TEN)
		VALUES (@TEN_TK, @MATKHAU, @LOAI_TK, @HO, @TEN)
	END
GO


CREATE	PROC	DANGNHAP__UPDATE
@TEN_TK		VARCHAR(20),
@MATKHAU	VARCHAR(100),
@LOAI_TK		INT,
@HO			NVARCHAR(10),
@TEN		NVARCHAR(20)
AS
	BEGIN
		UPDATE	DANGNHAP
		SET	MATKHAU = @MATKHAU, LOAI_TK = @LOAI_TK, HO = @HO, TEN = @TEN
		WHERE TEN_TK = @TEN_TK
	END
GO


CREATE	PROC	DANGNHAP__DELETE
@TEN_TK	VARCHAR(20)
AS
	BEGIN
		DELETE FROM DANGNHAP
		WHERE TEN_TK = @TEN_TK
	END
GO