USE OCEAN_HOSTEL
GO


CREATE PROC	PROC__PHONG_GetEmptyList	--	Phòng còn dư chỗ
AS
BEGIN
	SELECT p.*, lp.TENLOAIPHG, lp.GIAPHG
	FROM PHONG p, LOAIPHONG lp
	WHERE p.DANGSUACHUA = 'False'
		AND p.SOLG_DANGO < p.SOLG_TOIDA
			AND lp.MALOAIPHG = p.MALOAIPHG
END
GO

--------------------------------------------------------
CREATE	PROC	PROC__PHONG__GetList
AS
BEGIN
	SELECT k.MAKHU, k.TENKHU, t.MATANG, t.TENTANG, p.MAPHG, p.TENPHG, p.SOLG_DANGO, p.SOLG_TOIDA, p.DANGSUACHUA, l.MALOAIPHG, l.TENLOAIPHG
	FROM PHONG p, TANG t, KHU k, LOAIPHONG l
	WHERE l.MALOAIPHG = p.MALOAIPHG
		AND t.MATANG = p.MATANG
		AND k.MAKHU = t.MAKHU
END
GO

--------------------------------------------------------
CREATE PROC	PROC__PHONG__INSERT
@TENPHG			NVARCHAR(15),
@SOLG_TOIDA		INT,
@MATANG			VARCHAR(10),
@MALOAIPHG		VARCHAR(15),
@DANGSUACHUA	BIT
AS
BEGIN
	DECLARE @#MAPHG VARCHAR(10)
	SELECT @#MAPHG = dbo.FUNC__PHONG__GetNextID()
	
	INSERT INTO PHONG(MAPHG, TENPHG, SOLG_TOIDA, MATANG, MALOAIPHG, DANGSUACHUA)
	VALUES (@#MAPHG, @TENPHG, @SOLG_TOIDA, @MATANG, @MALOAIPHG, @DANGSUACHUA)
	
	
	EXEC PROC__DICHVU_PHONG__INSERT
		 @MADICHVU = 'DVU0000001',
		 @MAPHG = @#MAPHG
	
	EXEC PROC__DICHVU_PHONG__INSERT
		 @MADICHVU = 'DVU0000002',
		 @MAPHG = @#MAPHG
END
GO


--------------------------------------------------------
CREATE	PROC	PROC__PHONG__DELETE
@MAPHG	VARCHAR(10)
AS
BEGIN
	DELETE FROM DICHVU_PHONG
	WHERE MAPHG = @MAPHG
		AND MADICHVU = 'DVU0000001'
		OR	MADICHVU = 'DVU0000002'
	
	DELETE FROM PHONG
	WHERE MAPHG = @MAPHG
END
GO


--------------------------------------------------------
CREATE	PROC	PROC__PHONG__UPDATE
@MAPHG			VARCHAR(10),
@TENPHG			NVARCHAR(15),
@SOLG_TOIDA		INT,
@MATANG			VARCHAR(10),
@MALOAIPHG		VARCHAR(15),
@DANGSUACHUA	BIT
AS
BEGIN
	UPDATE PHONG
	SET TENPHG = @TENPHG,
		SOLG_TOIDA = @SOLG_TOIDA,
		MATANG = @MATANG,
		MALOAIPHG = @MALOAIPHG,
		DANGSUACHUA = @DANGSUACHUA
	WHERE MAPHG = @MAPHG
END
GO


--------------------------------------------------------
CREATE	PROC	PROC__PHONG__LayThongTinLoaiPhongTheoTenPhong
@TENPHG	NVARCHAR(15)
AS
BEGIN
	SELECT lp.*
	FROM PHONG p, LOAIPHONG lp
	WHERE p.TENPHG = @TENPHG
		AND lp.MALOAIPHG = p.MALOAIPHG
END
GO