USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__HOADON_DICHVU__INSERT
@MAHOADON	VARCHAR(15)
AS
BEGIN
	DECLARE @MAPHG VARCHAR(10)
	SELECT @MAPHG = MAX(MAPHG)		--	Lấy ra mã phòng của hoá đơn
	FROM HOADON
	WHERE MAHOADON = @MAHOADON
	
	
	---------------------------------------------------------
	SELECT p.MAPHG, dv.MADICHVU, dv.TENDICHVU, dv.GIADICHVU
	INTO #TEMP
	FROM PHONG p, DICHVU_PHONG dp, DICHVU dv
	WHERE p.MAPHG = @MAPHG
		AND dp.MAPHG = p.MAPHG
		AND dv.MADICHVU = dp.MADICHVU
		AND ((dv.TENDICHVU <> N'Tiền điện') 
			AND (dv.TENDICHVU <> N'Tiền nước'))
		
	
	---------------------------------------------------------
	WHILE (SELECT COUNT(*) FROM #TEMP) > 0
	BEGIN
		DECLARE @#MAPHG VARCHAR(10)
		DECLARE @#MADVU	VARCHAR(10)
		DECLARE @#TENDVU NVARCHAR(20)
		DECLARE @#GIADVU INT
		
		
		SELECT TOP 1 @#MAPHG = MAPHG,
					 @#MADVU = MADICHVU,
					 @#TENDVU = TENDICHVU,
					 @#GIADVU = GIADICHVU
		FROM #TEMP
		
		
		INSERT INTO HOADON_DICHVU(MAHOADON, MADICHVU, TENDICHVU, GIADICHVU)
		VALUES (@MAHOADON, @#MADVU, @#TENDVU, @#GIADVU)
		
		
		DELETE FROM #TEMP
		WHERE MAPHG = @#MAPHG
			AND MADICHVU = @#MADVU
	END
END
GO


--------------------------------------------------------------
CREATE	PROC	PROC__HOADON_DICHVU__LayDanhSachDichVuTheoMaHoaDon
@MAHOADON	VARCHAR(15)
AS
BEGIN
	SELECT *
	FROM HOADON_DICHVU
	WHERE MAHOADON = @MAHOADON
END
GO