USE OCEAN_HOSTEL
GO



CREATE	PROC	PROC__KHACH__TonTaiSoCanCuoc
@SOCANCUOC	VARCHAR(20)
AS
BEGIN
	SELECT COUNT(*)
	FROM KHACH
	WHERE SOCANCUOC = @SOCANCUOC
END
GO

-------------------------------------------
CREATE	PROC	PROC__KHACH__GetListByRoomID
@MAPHG	VARCHAR(10)
AS
BEGIN
	SELECT (kh.HO + ' ' + kh.TEN) AS HOTEN, kh.MAKHACH
	FROM KHACH kh, KHACH_HOPDONG khd, HOPDONG hd, PHONG ph
	WHERE khd.MAKHACH = kh.MAKHACH
		AND khd.MAHOPDONG = hd.MAHOPDONG
		AND ph.MAPHG = hd.MAPHG
		AND ph.MAPHG = @MAPHG
END
GO


-------------------------------------------
CREATE	PROC	PROC__KHACH__GetList
AS
BEGIN
	SELECT kh.*, ph.TENPHG, ph.MAPHG
	FROM KHACH kh, KHACH_HOPDONG khd, HOPDONG hd, PHONG ph
	WHERE kh.MAKHACH = khd.MAKHACH
		AND hd.MAHOPDONG = khd.MAHOPDONG
		AND ph.MAPHG = hd.MAPHG
END
GO

--------------------------------------------
CREATE	PROC	PROC__KHACH__INSERT
@MAKHACH		VARCHAR(10),
@HO				NVARCHAR(10),
@TEN			NVARCHAR(30),
@GIOITINH		NVARCHAR(10),
@NGAYSINH		DATE,
@QUEQUAN		NVARCHAR(75),
@SOCANCUOC		VARCHAR(20),
@SODIENTHOAI	VARCHAR(15)
AS
BEGIN
	INSERT INTO KHACH(MAKHACH, HO, TEN, GIOITINH, NGAYSINH, QUEQUAN, SOCANCUOC, SODIENTHOAI)
	VALUES (@MAKHACH, @HO, @TEN, @GIOITINH, @NGAYSINH, @QUEQUAN, @SOCANCUOC, @SODIENTHOAI)
END
GO


--------------------------------------------
CREATE	PROC	PROC__KHACH__GetListByRoomID
@MAPHG VARCHAR(10)
AS
BEGIN
END




EXEC PROC__KHACH__INSERT
@HO = N'Nguyễn',
@TEN = N'Anh Tuấn',
@GIOITINH = 'Nam',
@NGAYSINH = '2000-09-01',
@QUEQUAN = N'Thanh Hoá',
@SOCANCUOC = '038200016566',
@SODIENTHOAI = '0333326585'
