USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__KHACH__INSERT
@HO				NVARCHAR(10),
@TEN			NVARCHAR(30),
@GIOITINH		NVARCHAR(10),
@NGAYSINH		DATE,
@QUEQUAN		NVARCHAR(75),
@SOCANCUOC		VARCHAR(20),
@SODIENTHOAI	VARCHAR(15)
AS
BEGIN
	DECLARE @NEXTID VARCHAR(10)
	SELECT @NEXTID = dbo.FUNC__KHACH__GetNextID()
	
	INSERT INTO KHACH(MAKHACH, HO, TEN, GIOITINH, NGAYSINH, QUEQUAN, SOCANCUOC, SODIENTHOAI)
	VALUES (@NEXTID, @HO, @TEN, @GIOITINH, @NGAYSINH, @QUEQUAN, @SOCANCUOC, @SODIENTHOAI)
END
GO


--------------------------------------------
CREATE	PROC	PROC__KHACH__GetListByRoomID
@MAPHG VARCHAR(10)
AS
BEGIN
END




EXEC PROC__KHACH__INSERT
@HO = N'Nguyễn',
@TEN = N'Anh Tuấn',
@GIOITINH = 'Nam',
@NGAYSINH = '2000-09-01',
@QUEQUAN = N'Thanh Hoá',
@SOCANCUOC = '038200016566',
@SODIENTHOAI = '0333326585'
