USE OCEAN_HOSTEL
GO


CREATE PROC	PROC__TANG__GetLastFloor_ByAreaID
@MAKHU	VARCHAR(10)
AS
BEGIN
	DECLARE	@MAX_FLOOR INT
	SELECT @MAX_FLOOR = MAX(CONVERT(INT, SUBSTRING(TENTANG, 6, LEN(TENTANG) - 5)))
	FROM TANG
	WHERE MAKHU = @MAKHU

	SELECT t.*, k.TENKHU
	FROM TANG t, KHU k
	WHERE k.MAKHU = @MAKHU
		AND t.MAKHU = k.MAKHU
		AND CONVERT(INT, SUBSTRING(TENTANG, 6, LEN(TENTANG) - 5)) = @MAX_FLOOR
END
GO

----------------------------------------------
CREATE PROC	PROC__TANG__GetList
AS
BEGIN
	SELECT k.MAKHU, k.TENKHU, t.MATANG, t.TENTANG
	FROM TANG t, KHU k
	WHERE t.MAKHU = k.MAKHU
	GROUP BY k.MAKHU, k.TENKHU, t.MATANG, t.TENTANG
	ORDER BY k.TENKHU, MAX(CONVERT(INT, SUBSTRING(t.TENTANG, 6, LEN(t.TENTANG) - 5)))
END
GO

----------------------------------------------
CREATE	PROC	PROC__TANG__INSERT
@MAKHU		VARCHAR(10)
AS
BEGIN
	DECLARE @MATANG VARCHAR(10)
	SELECT @MATANG = dbo.FUNC__TANG__GetNextID()	-- Tự lấy mã tiếp theo
	
	DECLARE @TENTANG NVARCHAR(15)
	SELECT @TENTANG = dbo.FUNC__TANG__GetNextFloorName(@MAKHU)
	
	INSERT INTO TANG(MAKHU, MATANG, TENTANG)
	VALUES (@MAKHU, @MATANG, @TENTANG)
END
GO


---------------------------------
CREATE	PROC	PROC__TANG__DETELE
@MATANG		VARCHAR(10)
AS
BEGIN
	DELETE FROM TANG
	WHERE MATANG = @MATANG
END
GO


---------------------------------
CREATE	PROC	PROC__TANG__UPDATE
@MATANG		VARCHAR(10),
@TENTANG	VARCHAR(15)
AS
BEGIN
	UPDATE	TANG
	SET TENTANG = @TENTANG
	WHERE MATANG = @MATANG
END
GO