USE OCEAN_HOSTEL
GO


CREATE PROC	PROC__HOPDONG__INSERT
@MAHOPDONG	VARCHAR(10),
@MAPHONG	VARCHAR(10),
@THOIHAN	INT,
@TIENCOC	INT
AS
BEGIN
	INSERT INTO HOPDONG(MAHOPDONG, MAPHG, THOIHAN, TIENCOC)
	VALUES (@MAHOPDONG, @MAPHONG, @THOIHAN, @TIENCOC)
END
GO