USE OCEAN_HOSTEL
GO


------------------------------------------
CREATE	FUNCTION	FUNC__HOADON__GetNextID()
RETURNS	VARCHAR(15)
AS
BEGIN
	DECLARE @MAXID INT

	SELECT @MAXID = CONVERT(INT, MAX(SUBSTRING(MAHOADON, 7, LEN(MAHOADON) - 6)))
	FROM HOADON
	
	---------------------------------
	IF (@MAXID IS NULL)
		SET @MAXID = '0'
	
	
	DECLARE @DISTANCE INT
	IF (LEN(@MAXID + 1) > LEN(@MAXID))	--	Trường hợp chữ số cuối cùng của đơn vị
		SET @DISTANCE = 9 - (LEN(@MAXID) + 1)
	ELSE
		SET @DISTANCE = 9 - LEN(@MAXID)
	
	---------------------------------
	DECLARE @RESULT VARCHAR(15)
	SET @RESULT = 'HOADON' + REPLICATE('0', @DISTANCE) + CONVERT(VARCHAR, @MAXID + 1)
	
	RETURN @RESULT + CONVERT(VARCHAR, @MAXID + 1)
END
GO



-------------------------------------------------------------
CREATE FUNCTION	FUNC__HOADON__TongTienDien(@MAPHG VARCHAR(10), 
											   @THANG	INT, @NAM INT)
RETURNS INT
AS
BEGIN

	RETURN(
		SELECT hdn.GIADIEN*dbo.FUNC__HOADON_DIENNUOC__SoDienTieuThu(@MAPHG, @THANG, @NAM)
		FROM HOADON hd, HOADON_DIENNUOC hdn
		WHERE hd.MAPHG = @MAPHG
			AND hd.NAM = @NAM
			AND hd.THANG = @THANG
			AND hdn.MAHOADON = hd.MAHOADON)
END
GO


-------------------------------------------------------
CREATE FUNCTION	FUNC__HOADON__TongTienNuoc(@MAPHG VARCHAR(10), 
											   @THANG	INT, @NAM INT)
RETURNS INT
AS
BEGIN

	RETURN(
		SELECT hdn.GIANUOC*dbo.FUNC__HOADON_DIENNUOC__SoNuocTieuThu(@MAPHG, @THANG, @NAM)
		FROM HOADON hd, HOADON_DIENNUOC hdn
		WHERE hd.MAPHG = @MAPHG
			AND hd.NAM = @NAM
			AND hd.THANG = @THANG
			AND hdn.MAHOADON = hd.MAHOADON)
END
GO


-------------------------------------------------------
CREATE FUNCTION	FUNC__HOADON_DIENNUOC__SoDienTieuThu(@MAPHG VARCHAR(10),
														 @THANG INT, @NAM INT)
RETURNS INT
AS
BEGIN
	DECLARE @THANGTRUOC	INT
	DECLARE @NAMTRUOC INT
	
	IF (@THANG - 1 = 0)
		BEGIN
			SET @THANGTRUOC = 12
			SET @NAMTRUOC = @NAM - 1
		END
	ELSE
		BEGIN
			SET @THANGTRUOC = @THANG - 1
			SET @NAMTRUOC = @NAM
		END
	
	
	DECLARE @SODIENTHANGNAY INT
	SELECT @SODIENTHANGNAY = hdn.SODIEN
	FROM PHONG p, HOADON hd, HOADON_DIENNUOC hdn
	WHERE hd.MAPHG = @MAPHG
		AND hd.NAM = @NAM
		AND hd.THANG = @THANG
		AND hdn.MAHOADON = hd.MAHOADON
	
	IF @SODIENTHANGNAY IS NULL
		RETURN CAST(N'Chưa nhập thông tin điện nước của tháng ' + 
		CONVERT(VARCHAR, @THANG) + N' năm ' + CONVERT(VARCHAR, @NAM)
		 + ' !' AS INT)
	
	
	DECLARE @SODIENTHANGTRUOC INT
	SELECT @SODIENTHANGTRUOC = hdn.SODIEN
	FROM HOADON hd, HOADON_DIENNUOC hdn
	WHERE hd.MAPHG = @MAPHG
		AND hd.THANG = @THANGTRUOC
		AND hd.NAM = @NAMTRUOC
		AND hdn.MAHOADON = hd.MAHOADON
		
		
	IF @SODIENTHANGTRUOC IS NULL
		SET @SODIENTHANGTRUOC = 0
		
	
	RETURN @SODIENTHANGNAY - @SODIENTHANGTRUOC
END
GO


---------------------------------------------------------------------
CREATE FUNCTION	FUNC__HOADON_DIENNUOC__SoNuocTieuThu(@MAPHG VARCHAR(10),
														 @THANG INT, @NAM INT)
RETURNS INT
AS
BEGIN
	
	DECLARE @SONUOCTHANGNAY INT
	SELECT @SONUOCTHANGNAY = hdn.SONUOC
	FROM PHONG p, HOADON hd, HOADON_DIENNUOC hdn
	WHERE hd.MAPHG = @MAPHG
		AND hd.NAM = @NAM
		AND hd.THANG = @THANG
		AND hdn.MAHOADON = hd.MAHOADON
	
	IF @SONUOCTHANGNAY IS NULL
		RETURN CAST(N'Chưa nhập thông tin điện nước của tháng ' + 
		CONVERT(VARCHAR, @THANG) + N' năm ' + CONVERT(VARCHAR, @NAM)
		 + ' !' AS INT)
	
	-----------------------------------------------------------------
	DECLARE @THANGTRUOC	INT
	DECLARE @NAMTRUOC INT
	
	IF (@THANG - 1 = 0)
		BEGIN
			SET @THANGTRUOC = 12
			SET @NAMTRUOC = @NAM - 1
		END
	ELSE
		BEGIN
			SET @THANGTRUOC = @THANG - 1
			SET @NAMTRUOC = @NAM
		END
	
	
	DECLARE @SONUOCTHANGTRUOC INT
	SELECT @SONUOCTHANGTRUOC = hdn.SONUOC
	FROM HOADON hd, HOADON_DIENNUOC hdn
	WHERE hd.MAPHG = @MAPHG
		AND hd.THANG = @THANGTRUOC
		AND hd.NAM = @NAMTRUOC
		AND hdn.MAHOADON = hd.MAHOADON
		
		
	IF @SONUOCTHANGTRUOC IS NULL
		SET @SONUOCTHANGTRUOC = 0
		
	
	RETURN @SONUOCTHANGNAY - @SONUOCTHANGTRUOC
END
GO

------------------------------------------------------------
CREATE	FUNCTION	FUNC__HOADON__TongTienDichVu (@MAPHG	VARCHAR(10),
												  @THANG	INT,
												  @NAM	INT)
RETURNS INT
AS
BEGIN
	DECLARE @TOTAL INT
	
	SELECT @TOTAL = SUM(dv.GIADICHVU)
	FROM DICHVU_PHONG dp, DICHVU dv
	WHERE dp.MAPHG = @MAPHG
		AND dv.MADICHVU = dp.MADICHVU
		AND dv.TENDICHVU <> N'Tiền điện'
		AND dv.TENDICHVU <> N'Tiền nước'


	IF (@TOTAL IS NULL)
		SET @TOTAL = 0
		
	RETURN @TOTAL
END
GO