USE OCEAN_HOSTEL
GO


EXEC PROC__KHACH_VIPHAM__GetList

CREATE	PROC	PROC__KHACH_VIPHAM__GetList
AS
BEGIN
	SELECT (kh.HO + ' ' + kh.TEN) AS HOTEN, vp.NOIDUNG, khvp.*
	FROM KHACH kh, KHACH_VIPHAM khvp, VIPHAM vp
	WHERE khvp.MAKHACH = kh.MAKHACH
		AND vp.MAVIPHAM = khvp.MAVIPHAM
END
GO


--------------------------------------------
CREATE	PROC	PROC__KHACH_VIPHAM__INSERT
@MAVIPHAM	VARCHAR(10),
@MAKHACH	VARCHAR(10),
@GHICHU		NVARCHAR(75)
AS
BEGIN
	INSERT INTO KHACH_VIPHAM(MAVIPHAM, MAKHACH, GHICHU)
	VALUES (@MAVIPHAM, @MAKHACH, @GHICHU)
END
GO


-----------------------------------------------
CREATE	PROC	PROC__KHACH_VIPHAM__DELETE
@MAVIPHAM	VARCHAR(10),
@MAKHACH	VARCHAR(10),
@THOIGIAN	DATETIME
AS
BEGIN
	DELETE FROM KHACH_VIPHAM
	WHERE MAKHACH = @MAKHACH
		AND MAVIPHAM = @MAVIPHAM
		AND THOIGIANVIPHAM = @THOIGIAN
END
GO


---------------------------------------------
CREATE	PROC	PROC__KHACH_VIPHAM__UPDATE
@MAVIPHAM	VARCHAR(10),
@MAKHACH	VARCHAR(10),
@THOIGIAN	DATETIME,
@GHICHU		NVARCHAR(75),
@TRANGTHAI	BIT
AS
BEGIN
	UPDATE KHACH_VIPHAM
	SET GHICHU = @GHICHU,
		DAGIAIQUYET = @TRANGTHAI
	WHERE MAKHACH = @MAKHACH
		AND MAVIPHAM = @MAVIPHAM
		AND THOIGIANVIPHAM = @THOIGIAN
END
GO