USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__KHACH_VIPHAM__GetList
AS
BEGIN
	SELECT (kh.HO + ' ' + kh.TEN) AS HOTEN, ph.TENPHG, vp.NOIDUNG, khvp.*
	FROM KHACH kh, KHACH_VIPHAM khvp, VIPHAM vp, KHACH_HOPDONG khd, HOPDONG hd, PHONG ph
	WHERE khvp.MAKHACH = kh.MAKHACH
		AND vp.MAVIPHAM = khvp.MAVIPHAM
		AND khd.MAKHACH = kh.MAKHACH
		AND hd.MAHOPDONG = khd.MAHOPDONG
		AND ph.MAPHG = hd.MAPHG
END
GO


--------------------------------------------
CREATE	PROC	PROC__KHACH_VIPHAM__INSERT
@MAVIPHAM	VARCHAR(10),
@MAKHACH	VARCHAR(10),
@GHICHU		NVARCHAR(75)
AS
BEGIN
	INSERT INTO KHACH_VIPHAM(MAVIPHAM, MAKHACH, GHICHU)
	VALUES (@MAVIPHAM, @MAKHACH, @GHICHU)
END
GO


-----------------------------------------------
CREATE	PROC	PROC__KHACH_VIPHAM__DELETE
@MAVIPHAM	VARCHAR(10),
@MAKHACH	VARCHAR(10),
@THOIGIAN	DATETIME
AS
BEGIN
	DELETE FROM KHACH_VIPHAM
	WHERE MAKHACH = @MAKHACH
		AND MAVIPHAM = @MAVIPHAM
		AND THOIGIANVIPHAM = @THOIGIAN
END
GO


---------------------------------------------
CREATE	PROC	PROC__KHACH_VIPHAM__UPDATE
@MAVIPHAM	VARCHAR(10),
@MAKHACH	VARCHAR(10),
@THOIGIAN	DATETIME
AS
BEGIN
	UPDATE KHACH_VIPHAM
	SET DAGIAIQUYET = 'True'
	WHERE MAKHACH = @MAKHACH
		AND MAVIPHAM = @MAVIPHAM
		AND THOIGIANVIPHAM = @THOIGIAN
END
GO