USE OCEAN_HOSTEL
GO


CREATE PROC	PROC__KHACH_HOPDONG__INSERT
@MAKHACH	VARCHAR(10),
@MAHOPDONG	VARCHAR(10)
AS
BEGIN
	INSERT INTO KHACH_HOPDONG(MAKHACH, MAHOPDONG)
	VALUES (@MAKHACH, @MAHOPDONG)
	
	DECLARE @MAPHG	VARCHAR(10)
	SELECT @MAPHG = MAPHG
	FROM HOPDONG
	WHERE MAHOPDONG = @MAHOPDONG
	
	UPDATE PHONG
	SET SOLG_DANGO = SOLG_DANGO + 1
	WHERE MAPHG = @MAPHG
	
	UPDATE KHACH
	SET TRANGTHAI = N'Đang ở'
	WHERE MAKHACH = @MAKHACH
END
GO


CREATE	PROC	PROC__KHACH_HOPDONG__HETHAN
@MAKHACH	VARCHAR(10),
@MAHOPDONG	VARCHAR(10)
AS
BEGIN
	
END
GO