-- Create a new database called 'OCEAN_HOSTEL'
-- Connect to the 'master' database to run this snippet
USE master
GO
-- Create the new database if it does not exist already
IF NOT EXISTS (
    SELECT name
        FROM sys.databases
        WHERE name = N'OCEAN_HOSTEL'
)
CREATE DATABASE OCEAN_HOSTEL
GO

USE OCEAN_HOSTEL
GO



CREATE	TABLE   NGUOIDUNG
(
    TENDN           VARCHAR(30),
    MATKHAU         VARCHAR(100)						NOT NULL,   --  Mật khẩu dài khi được mã hoá
    HO              NVARCHAR(10)						NOT NULL,
    TEN             NVARCHAR(30)						NOT NULL,
	DANGNHAPLANDAU	BIT									NOT NULL		DEFAULT 'True',

    CONSTRAINT      PK__NGUOIDUNG						PRIMARY KEY(TENDN)
);


INSERT	INTO	NGUOIDUNG(TENDN, MATKHAU, HO, TEN)
VALUES ('admin', 'admin', N'Anh', N'Tuấn')


CREATE  TABLE   KHU
(
    MAKHU           VARCHAR(10),
    TENKHU          NVARCHAR(15)						NOT NULL,

    CONSTRAINT      PK__KHU								PRIMARY KEY(MAKHU),
    CONSTRAINT      UN__KHU								UNIQUE(TENKHU)
);


CREATE  TABLE   TANG
(
    MATANG          VARCHAR(10),
    TENTANG         NVARCHAR(15)						NOT NULL,
    MAKHU           VARCHAR(10)							NOT NULL,

    CONSTRAINT      PK__TANG							PRIMARY KEY(MATANG),
    CONSTRAINT      FK__TANG__MAKHU						FOREIGN KEY(MAKHU)  REFERENCES KHU(MAKHU)
);


CREATE  TABLE   LOAIPHONG
(
    MALOAIPHG       VARCHAR(15),
    TENLOAIPHG      NVARCHAR(15)						NOT NULL,
    GIAPHG          INT									NOT NULL,

    CONSTRAINT      PK__LOAIPHONG						PRIMARY KEY(MALOAIPHG),
    CONSTRAINT      UN__LOAIPHONG						UNIQUE(TENLOAIPHG)
);


CREATE  TABLE   PHONG
(
    MAPHG           VARCHAR(10),
    TENPHG          NVARCHAR(15)						NOT NULL,
    SOLG_TOIDA      INT									NOT NULL,
    SOLG_DANGO      INT									NOT NULL            DEFAULT 0,
    DANGSUACHUA     BIT									NOT NULL            DEFAULT 'False',
    MATANG          VARCHAR(10)							NOT NULL,
    MALOAIPHG       VARCHAR(15)							NOT NULL,

    CONSTRAINT      PK__PHONG							PRIMARY KEY(MAPHG),
    CONSTRAINT      FK__PHONG__MATANG					FOREIGN KEY(MATANG) REFERENCES TANG(MATANG),
    CONSTRAINT      FK__PHONG__MALOAIPHG				FOREIGN KEY(MALOAIPHG)  REFERENCES LOAIPHONG(MALOAIPHG),
    CONSTRAINT		UN__PHONG__TENPHG					UNIQUE(TENPHG)
);


CREATE  TABLE   THIETBI
(
    MATBI           VARCHAR(10),
    TENTBI          NVARCHAR(25)						NOT NULL,
    GIATBI          INT									NOT NULL,
    NGAYNHAP        DATE								NOT NULL            DEFAULT GETDATE(),
    SOLG_PHANBO     INT									NOT NULL            DEFAULT 0,
    SOLG_TON        INT									NOT NULL,

    CONSTRAINT      PK__THIETBI							PRIMARY KEY(MATBI),
    CONSTRAINT      UN__THIETBI							UNIQUE(TENTBI)
);


CREATE  TABLE   THIETBI_PHONG
(
    MATBI           VARCHAR(10),
    MAPHG           VARCHAR(10),
    THOIGIANCAP     DATETIME							DEFAULT GETDATE(),

    CONSTRAINT      PK__THIETBI_PHONG					PRIMARY KEY(MAPHG, MATBI, THOIGIANCAP),
    CONSTRAINT		FK__THIETBI_PHONG__MAPHG			FOREIGN KEY(MAPHG)	REFERENCES PHONG(MAPHG),
    CONSTRAINT		FK__THIETBI_PHONG__MATBI			FOREIGN	KEY(MATBI)	REFERENCES THIETBI(MATBI)
);


CREATE  TABLE   HOPDONG
(
    MAHOPDONG       VARCHAR(10),
    MAPHG           VARCHAR(10)							NOT NULL,
    THOIHAN         INT									NOT NULL,
    THOIGIANTAO     DATETIME							NOT NULL            DEFAULT GETDATE(),
    TRANGTHAI       NVARCHAR(15)						NOT NULL            DEFAULT N'Có hiệu lực',
    TIENCOC         INT									NOT NULL            DEFAULT 0,
    DATRACOC        BIT									NOT NULL            DEFAULT 'False',                --  Đã trả cọc

    CONSTRAINT      PK__HOPDONG							PRIMARY KEY(MAHOPDONG),
    CONSTRAINT      FK__HOPDONG__MAPHONG				FOREIGN KEY(MAPHG)  REFERENCES PHONG(MAPHG),
    CONSTRAINT      CK__HOPDONG__TRANGTHAI				CHECK(TRANGTHAI IN (N'Có hiệu lực', N'Hết hiệu lực'))
);


CREATE  TABLE   KHACH
(
    MAKHACH         VARCHAR(10),
    HO              NVARCHAR(10)						NOT NULL,
    TEN             NVARCHAR(30)						NOT NULL,
    GIOITINH        NVARCHAR(10)						NOT NULL            DEFAULT N'Không biết',
    NGAYSINH        DATE								NOT NULL,
    QUEQUAN         NVARCHAR(75)						NOT NULL,
    SOCANCUOC       VARCHAR(20)							NOT NULL,
    SODIENTHOAI     VARCHAR(15)							NULL,
    TRANGTHAI       NVARCHAR(15)						NOT NULL            DEFAULT N'Đang ở',

    CONSTRAINT      PK__KHACH							PRIMARY KEY(MAKHACH),
    CONSTRAINT      CK__KHACH__TRANGTHAI				CHECK(TRANGTHAI IN (N'Đang ở', N'Tạm vắng', N'', N'Hết hợp đồng')),
    CONSTRAINT      CK__KHACH__GIOITINH					CHECK(GIOITINH IN (N'Nam', N'Nữ', N'Khác', N'Không biết')),
    CONSTRAINT      UN__KHACH__SOCANCUOC				UNIQUE(SOCANCUOC)
);


CREATE  TABLE   KHACH_HOPDONG
(
    MAHOPDONG       VARCHAR(10),
    MAKHACH         VARCHAR(10),

    CONSTRAINT      PK__KHACH_HOPDONG           		PRIMARY KEY(MAKHACH, MAHOPDONG),
    CONSTRAINT		FK__KHACH_HOPDONG__MAKHACH			FOREIGN KEY(MAKHACH)	REFERENCES KHACH(MAKHACH),
    CONSTRAINT		FK__KHACH_HOPDONG__MAHOPDONG		FOREIGN KEY(MAHOPDONG)	REFERENCES HOPDONG(MAHOPDONG)
);


CREATE	TABLE	VIPHAM
(
	MAVIPHAM		VARCHAR(10),
	NOIDUNG			NVARCHAR(75)						NOT NULL,
	HINHPHAT		NVARCHAR(75)						NOT NULL,
	
	CONSTRAINT		PK__VIPHAM							PRIMARY KEY(MAVIPHAM),
	CONSTRAINT		UN__VIPHAM__NOIDUNG					UNIQUE(NOIDUNG)
);


CREATE	TABLE	KHACH_VIPHAM
(
	MAKHACH			VARCHAR(10),
	MAVIPHAM		VARCHAR(10),
	THOIGIANVIPHAM	DATETIME							DEFAULT GETDATE(),
	GHICHU			NVARCHAR(75)						NOT NULL,
	DAGIAIQUYET		BIT									NOT NULL		DEFAULT	'False',
	
	CONSTRAINT		PK__KHACH_VIPHAM					PRIMARY KEY(MAKHACH, MAVIPHAM, THOIGIANVIPHAM),
	CONSTRAINT		FK__KHACH_VIPHAM__MAKHACH			FOREIGN KEY(MAKHACH)	REFERENCES KHACH(MAKHACH),
	CONSTRAINT		FK__KHACH_VIPHAM__MAVIPHAM			FOREIGN	KEY(MAVIPHAM)	REFERENCES VIPHAM(MAVIPHAM)
);


CREATE  TABLE   DICHVU
(
    MADICHVU        VARCHAR(10),
    TENDICHVU       NVARCHAR(20)						NOT NULL,
    GIADICHVU       INT									NOT NULL,
    BATBUOC			BIT									NOT NULL		DEFAULT	'False'

    CONSTRAINT      PK__DICHVU							PRIMARY KEY(MADICHVU),
    CONSTRAINT      UN__DICHVU__TENDICHVU				UNIQUE(TENDICHVU)
);


CREATE  TABLE   DICHVU_PHONG
(
    MADICHVU        VARCHAR(10),
    MAPHG           VARCHAR(10),
    NGAYDANGKY		DATETIME							NOT NULL		DEFAULT	GETDATE(),

    CONSTRAINT      PK__DICHVU_PHONG					PRIMARY KEY(MADICHVU, MAPHG),
    CONSTRAINT      FK__DICHVU_PHONG__MADICHVU			FOREIGN KEY(MADICHVU)   REFERENCES DICHVU(MADICHVU),
    CONSTRAINT      FK__DICHVU_PHONG__MAPHONG			FOREIGN KEY(MAPHG)  REFERENCES  PHONG(MAPHG)
);


CREATE  TABLE   HOADON
(
    MAHOADON        VARCHAR(15),
    MAPHG           VARCHAR(10)							NOT NULL,
    THANG           INT									NOT NULL,
    NAM             INT									NOT NULL,
    DATHANHTOAN		BIT									NOT NULL        DEFAULT 'False',     --  Thanh toán đủ hay chưa
    TIENPHONG		INT									NOT NULL,							 --  Giá cũ vẫn giữ nguyên khi loại phòng thay đổi giá

    CONSTRAINT      PK__HOADON							PRIMARY KEY(MAHOADON),
    CONSTRAINT      UN__HOADON							UNIQUE(MAPHG, THANG, NAM),
    CONSTRAINT      FK__HOADON__MAPHG					FOREIGN KEY(MAPHG)  REFERENCES PHONG(MAPHG)
);


CREATE  TABLE   HOADON_DIENNUOC     --  1 hoá đơn chỉ có một thông tin điện nước (cho một tháng) ==> 1:1
(
    MAHOADON        VARCHAR(15),
    GIADIEN         INT                                 NOT NULL,
    GIANUOC         INT                                 NOT NULL,
    SODIEN          INT                                 NOT NULL,
    SONUOC          INT                                 NOT NULL,

    CONSTRAINT      PK__HOADON_DIENNUOC                 PRIMARY KEY(MAHOADON),  --  Quan hệ 1:1
    CONSTRAINT      FK__HOADON_DIENNUOC__MAHOADON       FOREIGN KEY(MAHOADON)   REFERENCES HOADON(MAHOADON)
);


CREATE  TABLE   HOADON_DICHVU   --  1 hoá đơn có thể nhiều dịch vụ và ngược lại ==> n:n
(
    MAHOADON        VARCHAR(15),
    MADICHVU        VARCHAR(10),
    TENDICHVU       NVARCHAR(20),
    GIADICHVU       INT,

    CONSTRAINT      PK__HOADON_DICHVU                   PRIMARY KEY(MAHOADON, MADICHVU),
    CONSTRAINT      FK__HOADON_DICHVU__MAHOADON         FOREIGN KEY(MAHOADON)   REFERENCES HOADON(MAHOADON)
);