USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__HOADON_DIENNUOC__INSERT
@MAHOADON	VARCHAR(15),
@SODIEN		INT,
@SONUOC		INT
AS
BEGIN
	DECLARE @MAPHG VARCHAR(10)
	SELECT @MAPHG = MAX(MAPHG)		--	Lấy ra mã phòng của hoá đơn
	FROM HOADON
	WHERE MAHOADON = @MAHOADON
	
	---------------------------------------------------------
	DECLARE @#GIADIEN INT
	DECLARE @#GIANUOC INT
	
	SELECT @#GIADIEN = MAX(GIADICHVU)
	FROM DICHVU
	WHERE TENDICHVU = N'Tiền điện'
	
	SELECT @#GIANUOC = MAX(GIADICHVU)
	FROM DICHVU
	WHERE TENDICHVU = N'Tiền nước'
	
	
	INSERT INTO HOADON_DIENNUOC(MAHOADON, GIADIEN, GIANUOC, SODIEN, SONUOC)
	VALUES (@MAHOADON, @#GIADIEN, @#GIANUOC, @SODIEN, @SONUOC)
END
GO


---------------------------------------------------------------------
CREATE	PROC	PROC__HOADON_DIENNUOC__LayThongTinThangTruoc
@MAPHG	VARCHAR(10),
@THANG	INT,
@NAM	INT
AS
BEGIN
	DECLARE @THANGTRUOC INT
	DECLARE @NAMTRUOC	INT
	
	IF (@THANG - 1) = 0
		BEGIN
			SET @THANGTRUOC = 12
			SET @NAMTRUOC = @NAM - 1
		END
	ELSE
		BEGIN
			SET @THANGTRUOC = @THANG - 1
			SET @NAMTRUOC = @NAM
		END
	
	
	SELECT hdn.*
	FROM HOADON hd, HOADON_DIENNUOC hdn
	WHERE hd.MAPHG = @MAPHG
		AND hd.NAM = @NAMTRUOC
		AND hd.THANG = @THANGTRUOC
		AND hdn.MAHOADON = hd.MAHOADON
END
GO


-------------------------------------------------------------ư
CREATE	PROC	PROC__HOADON_DIENNUOC__LayThongTinThangHienTai
@MAPHG	VARCHAR(10),
@THANG	INT,
@NAM	INT
AS
BEGIN
	SELECT hdn.*
	FROM HOADON hd, HOADON_DIENNUOC hdn
	WHERE hd.MAPHG = @MAPHG
		AND hd.NAM = @NAM
		AND hd.THANG = @THANG
		AND hdn.MAHOADON = hd.MAHOADON
END
GO