USE OCEAN_HOSTEL
GO


CREATE FUNCTION	FUNC__THIETBI_PHONG__GetListByRoomID(@MAPHG VARCHAR(10))
RETURNS TABLE
AS
	RETURN
		(
			SELECT tp.*, tb.TENTBI
			FROM THIETBI_PHONG tp, THIETBI tb
			WHERE tp.MAPHG = @MAPHG
				AND tp.MATBI = tb.MATBI
		)