USE OCEAN_HOSTEL
GO



CREATE	PROC	PROC__THIETBI_PHONG__GetListByRoomID
@MAPHG	VARCHAR(10)
AS
BEGIN
	SELECT tp.*, tb.TENTBI
			FROM THIETBI_PHONG tp, THIETBI tb
			WHERE tp.MAPHG = @MAPHG
				AND tp.MATBI = tb.MATBI
END
GO


---------------------------------
CREATE	PROC	PROC__THIETBI_PHONG__INSERT
@MATBI	VARCHAR(10),
@MAPHG	VARCHAR(10)
AS
BEGIN
	INSERT INTO THIETBI_PHONG(MATBI, MAPHG)
	VALUES (@MATBI, @MAPHG)
	
	UPDATE THIETBI
	SET SOLG_PHANBO = SOLG_PHANBO + 1,
		SOLG_TON = SOLG_TON - 1
	WHERE MATBI = @MATBI
END
GO


---------------------------------
CREATE	PROC	PROC__THIETBI_PHONG__DETELE
@MATBI			VARCHAR(10),
@MAPHG			VARCHAR(10),
@THOIGIANCAP	DATETIME
AS
BEGIN
	DELETE FROM THIETBI_PHONG
	WHERE MATBI = @MATBI
		AND MAPHG = @MAPHG
		AND THOIGIANCAP = @THOIGIANCAP
	
	UPDATE THIETBI
	SET SOLG_PHANBO = SOLG_PHANBO - 1,
		SOLG_TON = SOLG_TON + 1
	WHERE MATBI = @MATBI
END
GO