USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__NGUOIDUNG__INSERT
@TENDN		VARCHAR(30),
@MATKHAU	VARCHAR(100),
@HO			NVARCHAR(10),
@TEN		NVARCHAR(30)
AS
BEGIN
	INSERT INTO NGUOIDUNG(TENDN, MATKHAU, HO, TEN)
	VALUES (@TENDN, @MATKHAU, @HO, @TEN)
END 
GO


CREATE	PROC	PROC__NGUOIDUNG__UPDATE
@TENDN		VARCHAR(30),
@MATKHAU	VARCHAR(100),
@HO			NVARCHAR(10),
@TEN		NVARCHAR(30)
AS
BEGIN
	UPDATE NGUOIDUNG
	SET MATKHAU = @MATKHAU,
		HO = @HO, TEN = @TEN,
		TENDN = @TENDN
	WHERE TENDN = @TENDN
END
GO