USE OCEAN_HOSTEL
GO


CREATE PROC	PROC__VIPHAM__INSERT
@NOIDUNG	NVARCHAR(75),
@HINHPHAT	NVARCHAR(75)
AS
BEGIN
	DECLARE @NEXTID VARCHAR(10)
	SELECT @NEXTID = dbo.FUNC__VIPHAM__GetNextID()
	
	INSERT INTO VIPHAM(MAVIPHAM, NOIDUNG, HINHPHAT)
	VALUES (@NEXTID, @NOIDUNG, @HINHPHAT)
END
GO

-------------------------------------------------------
CREATE	PROC	PROC__VIPHAM__DELETE
@MAVIPHAM	VARCHAR(10)
AS
BEGIN
	DELETE FROM VIPHAM
	WHERE MAVIPHAM = @MAVIPHAM
END
GO

-------------------------------------------------------
CREATE	PROC	PROC__VIPHAM__UPDATE
@MAVIPHAM	VARCHAR(10),
@NOIDUNG	NVARCHAR(75),
@HINHPHAT	NVARCHAR(75)
AS
BEGIN
	UPDATE VIPHAM
	SET NOIDUNG = @NOIDUNG,
		HINHPHAT = @HINHPHAT
	WHERE MAVIPHAM = @MAVIPHAM
END
GO