USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__HOADON_DIENNUOC__INSERT
@MAHOADON	VARCHAR(15),
@SODIEN		INT,
@SONUOC		INT
AS
BEGIN
	DECLARE @MAPHG VARCHAR(10)
	SELECT @MAPHG = MAX(MAPHG)		--	Lấy ra mã phòng của hoá đơn
	FROM HOADON
	WHERE MAHOADON = @MAHOADON
	
	---------------------------------------------------------
	DECLARE @#GIADIEN INT
	DECLARE @#GIANUOC INT
	
	SELECT @#GIADIEN = MAX(GIADICHVU)
	FROM DICHVU
	WHERE TENDICHVU = N'Tiền điện'
	
	SELECT @#GIANUOC = MAX(GIADICHVU)
	FROM DICHVU
	WHERE TENDICHVU = N'Tiền nước'
	
	
	INSERT INTO HOADON_DIENNUOC(MAHOADON, GIADIEN, GIANUOC, SODIEN, SONUOC)
	VALUES (@MAHOADON, @#GIADIEN, @#GIANUOC, @SODIEN, @SONUOC)
END