USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__DICHVU__DELETE
@MADICHVU		VARCHAR(10)
AS
BEGIN
	DELETE FROM DICHVU
	WHERE MADICHVU = @MADICHVU
END
GO


------------------------------------
CREATE	PROC	PROC__DICHVU__INSERT
@TENDICHVU		NVARCHAR(20),
@GIADICHVU		INT,
@BATBUOC		BIT
AS
BEGIN
	DECLARE @NEXTID VARCHAR(10)
	SELECT @NEXTID = dbo.FUNC__DICHVU__GetNextID()	--	Tự động lấy mã tiếp theo
	
	INSERT INTO DICHVU(MADICHVU, TENDICHVU, GIADICHVU, BATBUOC)
	VALUES (@NEXTID, @TENDICHVU, @GIADICHVU, @BATBUOC)
END
GO


-----------------------------------------------------------------------
CREATE	PROC	PROC__DICHVU__UPDATE
@MADICHVU		VARCHAR(10),
@TENDICHVU		NVARCHAR(20),
@GIADICHVU		INT,
@BATBUOC		BIT
AS
BEGIN
	UPDATE	DICHVU
	SET TENDICHVU = @TENDICHVU,
		GIADICHVU = @GIADICHVU,
		BATBUOC = @BATBUOC
	WHERE MADICHVU = @MADICHVU
END
GO


--------------------------------------------------
CREATE	PROC	PROC__DICHVU__IsReferenced
@MADICHVU	VARCHAR(10)
AS
BEGIN
	SELECT COUNT(MADICHVU)
	FROM DICHVU_PHONG
	WHERE MADICHVU = @MADICHVU
END
GO


-----------------------------------------------
CREATE	PROC	PROC__DICHVU__LayThongTinDienNuoc
AS
BEGIN
	SELECT *
	FROM DICHVU
	WHERE TENDICHVU = N'Tiền điện'
		OR TENDICHVU = N'Tiền nước'
END
GO

exec PROC__DICHVU__LayThongTinDienNuoc