USE OCEAN_HOSTEL
GO


CREATE	PROC	PROC__PHONG__GetList
AS
BEGIN
	SELECT k.MAKHU, k.TENKHU, t.MATANG, t.TENTANG, p.MAPHG, p.TENPHG, p.SOLG_DANGO, p.SOLG_TOIDA, p.DANGSUACHUA, l.MALOAIPHG, l.TENLOAIPHG
	FROM PHONG p, TANG t, KHU k, LOAIPHONG l
	WHERE l.MALOAIPHG = p.MALOAIPHG
		AND t.MATANG = p.MATANG
		AND k.MAKHU = t.MAKHU
END
GO

--------------------------------------------------------
CREATE	PROC	PROC__PHONG__INSERT
@TENPHG			NVARCHAR(15),
@SOLG_TOIDA		INT,
@MATANG			VARCHAR(10),
@MALOAIPHG		VARCHAR(15),
@DANGSUACHUA	BIT
AS
BEGIN
	DECLARE @MAPHG VARCHAR(10)
	SELECT @MAPHG = dbo.FUNC__PHONG__GetNextID()
	
	INSERT INTO PHONG(MAPHG, TENPHG, SOLG_TOIDA, MATANG, MALOAIPHG, DANGSUACHUA)
	VALUES (@MAPHG, @TENPHG, @SOLG_TOIDA, @MATANG, @MALOAIPHG, @DANGSUACHUA)
END
GO


--------------------------------------------------------
CREATE	PROC	PROC__PHONG__DELETE
@MAPHG	VARCHAR(10)
AS
BEGIN
	DELETE FROM PHONG
	WHERE MAPHG = @MAPHG
END
GO


--------------------------------------------------------
CREATE	PROC	PROC__PHONG__UPDATE
@MAPHG			VARCHAR(10),
@TENPHG			NVARCHAR(15),
@SOLG_TOIDA		INT,
@MATANG			VARCHAR(10),
@MALOAIPHG		VARCHAR(15),
@DANGSUACHUA	BIT
AS
BEGIN
	UPDATE PHONG
	SET TENPHG = @TENPHG,
		SOLG_TOIDA = @SOLG_TOIDA,
		MATANG = @MATANG,
		MALOAIPHG = @MALOAIPHG,
		DANGSUACHUA = @DANGSUACHUA
	WHERE MAPHG = @MAPHG
END